[[imports]]
path="github.com/ojroques/hugo-researcher"


[params.navigation]
logo=""

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
